version: "3.8"

services:
  app:
    build:
      context: ./Flask_app
    container_name: app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: myDBpassword
      DB_NAME: metrics
    depends_on:
      - database
  
  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: myDBpassword
      MYSQL_DATABASE: metrics
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: